version: '3'

tasks:
  check:
    desc: Run tests and lint
    cmds:
      - bash gradlew check

  fix:
    desc: Format Kotlin files
    cmds:
      - bash gradlew ktfmtFormat

  build:
    desc: Build modules
    cmds:
      - bash gradlew build

  publish:
    desc: Publish a module
    cmds:
      - bash gradlew {{.GRADLE_TARGET}}
    vars:
      GRADLE_TARGET:
        sh: |
          case "{{.MODULE}}" in
            commons-convention) echo "-p commons-convention publish" ;;
            *) echo ":{{.MODULE}}:publish" ;;
          esac
