version: '3'

tasks:
  build:
    desc: Build security library module
    cmds:
      - ../gradlew :security:build
  check:
    desc: Run tests and quality checks for security module
    cmds:
      - ../gradlew :security:check
  fix:
    desc: Format security module code
    cmds:
      - ../gradlew :security:ktfmtFormat
