version: '3'

tasks:
  build:
    desc: Build Gradle convention plugins
    cmds:
      - ../gradlew -p . build
  check:
    desc: Run quality checks on Gradle convention plugins
    cmds:
      - ../gradlew -p . check
