name: CI

on:
  pull_request:
    branches: [dev, main]

permissions:
  contents: read
  packages: write

jobs:
  # ==========================================
  # PATH FILTERING
  # ==========================================
  changes:
    name: Detect Changed Paths
    runs-on: ubuntu-latest
    outputs:
      gradle: ${{ steps.filter.outputs.gradle }}
      pnpm: ${{ steps.filter.outputs.pnpm }}
      docs: ${{ steps.filter.outputs.docs }}
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Detect Changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            gradle:
              - 'gradle/**'
              - '.github/workflows/ci.yml'
            pnpm:
              - 'pnpm/**'
              - '.github/workflows/ci.yml'
            docs:
              - '**/*.md'
              - '.github/workflows/ci.yml'

  # ==========================================
  # GRADLE CI JOB
  # ==========================================
  gradle:
    name: Gradle Check
    needs: changes
    if: needs.changes.outputs.gradle == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set Up Gradle
        uses: ./.github/actions/setup-gradle

      - name: Run Check
        run: task gradle:check

  # ==========================================
  # PNPM CI JOB
  # ==========================================
  pnpm:
    name: PNPM Check
    needs: changes
    if: needs.changes.outputs.pnpm == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set Up PNPM
        uses: ./.github/actions/setup-pnpm

      - name: Run Check
        run: task pnpm:check

  # ==========================================
  # COMMIT CI JOB
  # ==========================================
  commitlint:
    name: Commit Check
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up Node
        uses: ./.github/actions/setup-node

      - name: Run Check
        env:
          FROM_SHA: ${{ github.event.pull_request.base.sha }}
          TO_SHA: ${{ github.event.pull_request.head.sha }}
        run: task commit:check

  # ==========================================
  # DOCUMENTATION CI JOB
  # ==========================================
  docs:
    name: Docs Check
    needs: changes
    if: needs.changes.outputs.docs == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set Up Node
        uses: ./.github/actions/setup-node

      - name: Run Docs Checks
        run: task docs:check
